services:
  postgres:
    ports:
      - ${BUTLER_POSTGRES_PORT:-5432}:5432
    volumes:
      - butler-postgres-data:/var/lib/postgresql/data

  redis:
    ports:
      - ${BUTLER_REDIS_PORT:-6379}:6379
    volumes:
      - butler-redis-data:/data

  orchestrator:
    ports:
      - ${BUTLER_ORCHESTRATOR_HTTP_PORT:-8080}:8080
      - ${BUTLER_ORCHESTRATOR_GRPC_PORT:-9090}:9090

volumes:
  butler-postgres-data:
  butler-redis-data:
